### ISSUE TITLE
Converting Lidar .las / .laz to .tif

### ISSUE THREAD

**Issue by RitaAguiar** [opengeos/lidar#22]
I would like to suggest a new feature to be able to convert a lidar .las / .laz to a .tif file.

**Comment by hafez-ahmad** [comment]
@RitaAguiar 
Arcgis pro and Arcgis 10 already have such functionality and there is a python package [laspy] for that. And geemap can read lidar file [geemap.read_lidar]. 

Thank you
Hafez
