### ISSUE TITLE
Numpy version 1.20.0 or greater throws AttributeError when running ExtractSinks

### ISSUE THREAD

**Issue by stephenwaltersNV5** [opengeos/lidar#34]
Thank you for this fantastic package!

* lidar version: 0.7.1
* numpy version: 1.24.4
* Python version: 3.8
* Operating System: Windows 10 Pro

### Description

Attempted to run the _ExtractSinks_ function but Numpy threw an AttributeError.

### What I Did

**Commands:**

```
lidar.ExtractSinks(in_dem=DEM,  min_size=min_area, out_dir=out_dir)
```

**Traceback:**

```
Loading data ...
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\hydro\lib\site-packages\lidar\filling.py", line 290, in ExtractSinks
    max_elev = np.float(np.max(dem[dem != no_data]))
  File "C:\Users\user\Miniconda3\envs\hydro\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

Offending lines of code:
![image](https://github.com/opengeos/lidar/assets/117768607/de4938f5-647f-477f-8faa-8445c4757e12)

The issue was resolved after replacing all references in the codebase from _np.float()_ to the python built-in _float()_.

**Comment by giswqs** [comment]
Thank you for reporting! Would you like to submit a pull request to fix this so that you can get credits for this? Thank you.
