### ISSUE TITLE
Minor bug/typo in lidar.ipynb

### ISSUE THREAD

**Issue by rafelafrance** [opengeos/lidar#36]
* lidar version: 0.7.2
* Python version: 3.8.18
* Operating System: Pop!_OS 22.04

### Description

While working thru the example notebook [lidar.ipynb](https://github.com/opengeos/lidar/blob/master/examples/lidar.ipynb), I could not open the zip file in cell 4.

### What I Did

To fix, change:
`with zipfile.ZipFile(zip_name, "r") as zip_ref:` to
`with zipfile.ZipFile(zip_path, "r") as zip_ref:`

Presumably, also change:
`with tarfile.open(zip_name, "r") as tar_ref:` to
`with tarfile.open(zip_path, "r") as tar_ref:`

**Comment by giswqs** [comment]
Can you submit a pull request to fix it? Thanks
